version: "3"
services:
    mysql:
      image: mysql:8.4.0
      container_name: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "chanos"
        TZ: "Asia/Seoul"
      volumes:
        - "${PWD}/volume:/var/lib/mysql"